// <auto-generated />
using System;
using AfishaVoenmeh.RegistrationService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AfishaVoenmeh.RegistrationService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202120758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AfishaVoenmeh.RegistrationService.Domain.EventRegistrationAggregate.EventRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CancelledAt");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RegisteredAt");

                    b.Property<int>("RegistrationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("RegistrationStatus");

                    b.HasKey("Id");

                    b.ToTable("EventRegistrations", (string)null);
                });

            modelBuilder.Entity("AfishaVoenmeh.RegistrationService.Domain.EventRegistrationAggregate.EventRegistration", b =>
                {
                    b.OwnsOne("AfishaVoenmeh.RegistrationService.Domain.EventRegistrationAggregate.ValueObjects.EventId", "EventId", b1 =>
                        {
                            b1.Property<Guid>("EventRegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("EventId");

                            b1.HasKey("EventRegistrationId");

                            b1.ToTable("EventRegistrations");

                            b1.WithOwner()
                                .HasForeignKey("EventRegistrationId");
                        });

                    b.OwnsOne("AfishaVoenmeh.RegistrationService.Domain.EventRegistrationAggregate.ValueObjects.UserId", "UserId", b1 =>
                        {
                            b1.Property<Guid>("EventRegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("UserId");

                            b1.HasKey("EventRegistrationId");

                            b1.ToTable("EventRegistrations");

                            b1.WithOwner()
                                .HasForeignKey("EventRegistrationId");
                        });

                    b.Navigation("EventId")
                        .IsRequired();

                    b.Navigation("UserId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
